name: Deploy (Build and Push Docker Image)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image name (lowercase)
        id: names
        shell: bash
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY}"
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "image=$IMAGE_NAME_LOWER" >> $GITHUB_OUTPUT

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.names.outputs.image }}:latest
            ${{ steps.names.outputs.image }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Notify deployment platform with the new image tag
      # - name: Deploy to Railway (optional)
      #   if: ${{ secrets.RAILWAY_TOKEN != '' }}
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      #     IMAGE: ${{ steps.names.outputs.image }}:${{ github.sha }}
      #   run: |
      #     npm i -g @railway/cli@3.20.0
      #     # Replace the following with your service-specific command.
      #     # This assumes your Railway service is configured for "Deploy from Docker image".
      #     # Example: railway images set --service <SERVICE_ID_OR_NAME> --image "$IMAGE"
      #     echo "Configured to push image $IMAGE; add your Railway deploy command here if desired."
